# Matrix operations with NumPy

In [5]:
import numpy as np

In [11]:
# Append a column to a matrix
"""
1 2 3       1 2 3 0
4 5 6 -->   4 5 6 0
7 8 9       7 8 9 0
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((3, 1))
np.c_[m, b]

array([[1., 2., 3., 0.],
       [4., 5., 6., 0.],
       [7., 8., 9., 0.]])

In [12]:
# Prepend a column to a matrix
"""
1 2 3       0 1 2 3
4 5 6 -->   0 4 5 6
7 8 9       0 7 8 9
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((3, 1))
np.c_[b, m]

array([[0., 1., 2., 3.],
       [0., 4., 5., 6.],
       [0., 7., 8., 9.]])

In [13]:
# Append a row to a matrix
"""
1 2 3       1 2 3
4 5 6 -->   4 5 6
7 8 9       7 8 9
            0 0 0
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((1, 3))
np.r_[m, b]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [0., 0., 0.]])

In [ ]:
# Prepend a row to a matrix
"""
1 2 3       0 0 0
4 5 6 -->   1 2 3
7 8 9       4 5 6
            7 8 9
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((1, 3))
np.r_[b, m]