# Matrix operations with NumPy

In [33]:
import numpy as np

In [34]:
# Append a column to a matrix
"""
1 2 3       1 2 3 0
4 5 6 -->   4 5 6 0
7 8 9       7 8 9 0
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((3, 1))
np.c_[m, b]

array([[1., 2., 3., 0.],
       [4., 5., 6., 0.],
       [7., 8., 9., 0.]])

In [35]:
# Prepend a column to a matrix
"""
1 2 3       0 1 2 3
4 5 6 -->   0 4 5 6
7 8 9       0 7 8 9
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((3, 1))
np.c_[b, m]

array([[0., 1., 2., 3.],
       [0., 4., 5., 6.],
       [0., 7., 8., 9.]])

In [36]:
# Append a row to a matrix
"""
1 2 3       1 2 3
4 5 6 -->   4 5 6
7 8 9       7 8 9
            0 0 0
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((1, 3))
np.r_[m, b]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [0., 0., 0.]])

In [37]:
# Prepend a row to a matrix
"""
1 2 3       0 0 0
4 5 6 -->   1 2 3
7 8 9       4 5 6
            7 8 9
"""
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.zeros((1, 3))
np.r_[b, m]

array([[0., 0., 0.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [38]:
# Iterate the rows of a matrix
"""
1 2 3
4 5 6
7 8 9

>> 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
"""
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for row in m:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [39]:
# Iterate the rows of a matrix
"""
1 2 3
4 5 6
7 8 9

>> 
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]
"""
# Note: m.T is not costly -- 
# just changes the 'strides' of the array 
# (stride: number of elements successive before 
# next array element (sub-array))
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for col in m.T:
    print(col)

[1 4 7]
[2 5 8]
[3 6 9]


In [40]:
# Get first/last row of a matrix
"""
1 2 3
4 5 6
7 8 9

>>
[1, 2, 3], [7, 8, 9]
"""
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m[0], m[-1]  # or m[0, :], m[-1, :]

(array([1, 2, 3]), array([7, 8, 9]))

In [41]:
# Get first/last column of a matrix
"""
1 2 3
4 5 6
7 8 9

>>
[1, 4, 7], [3, 6, 9]
"""
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m[:, 0], m[:, -1]

(array([1, 4, 7]), array([3, 6, 9]))

In [42]:
# What does divide by a scalar do?
"""
1 2 3
4 5 6 / 2
7 8 9
"""
# Divides all elements by the scalar
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int64)
m / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [43]:
# What does divide by a vector do?
"""
1 2 3
4 5 6 / [1 , 2, 3]
7 8 9
"""
# Divides by columns
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int64)
m / [1, 2, 3]

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [44]:
# How can you create a diagonal matrix from a vector?
"""
[1, 2, 3]
->
1 0 0
0 2 0
0 0 3
"""
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:
# How do you compute the sum of all elements?
"""
1 2 3
4 5 6
7 8 9

>> 45
"""
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.sum(m)

np.int64(45)

In [47]:
# How do you compute the sum for each column?
"""
1 2 3
4 5 6
7 8 9

>> [12, 15, 18]
"""
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.sum(m, axis=0)

array([12, 15, 18])

In [ ]:
# How do you compute the sum for each row?
"""
1 2 3
4 5 6
7 8 9

>> [6, 15, 24]
"""
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.sum(m, axis=1)

array([ 6, 15, 24])

In [52]:
# What is the output?
"""
1 2 3
4 5 6 - [1, 2, 3]
7 8 9
"""
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m - [1, 2, 3]

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [54]:
# Let p be 2D points. 
# Calculate the centroid of the points, mu, 
# and subtract it from each point.
"""
1 5 9 8
3 7 1 4
"""
p = np.array([[1, 5, 9, 8], [3, 7, 1, 4]])
mu = np.mean(p, axis=1)
(p.T - mu).T

array([[-4.75, -0.75,  3.25,  2.25],
       [-0.75,  3.25, -2.75,  0.25]])